'use client';

import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'vi';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations = {
    en: {
        'nav.features': 'Features',
        'nav.assets': 'Assets',
        'nav.pricing': 'Pricing',
        'nav.about': 'About',
        'nav.signin': 'Sign in',
        'nav.getstarted': 'Get Started',
        'hero.scroll': 'Scroll down',
        'intro.title': 'Manage your assets',
        'intro.subtitle': 'smarter.',
        'intro.description': 'The premium personal finance platform with realtime asset tracking. Minimalist design, focused on core data.',
        'intro.cta.primary': 'Get Started',
        'intro.cta.secondary': 'Explore Features',
        'features.title': 'Everything you need.',
        'features.subtitle': 'Complete control over your financial picture.',
        'features.realtime': 'Realtime Dashboard',
        'features.realtime.desc': 'Asset values updated every second with zero latency.',
        'features.multiasset': 'Multi-Asset',
        'features.multiasset.desc': 'Track crypto, forex, gold, and Vietnamese stocks—all in one unified portfolio.',
        'features.pl': 'P/L Tracking',
        'features.pl.desc': 'Realtime profit & loss calculations.',
        'features.advisor': 'AI Portfolio Advisor',
        'features.advisor.desc': 'Intelligent recommendations to optimize your portfolio allocation based on market conditions and risk profile.',
        'features.news': 'Asset News Updates',
        'features.news.desc': 'Stay informed with real-time news and market insights for all your tracked assets.',

        // Asset Types
        'assets.title': 'Track Every Asset',
        'assets.subtitle': 'Comprehensive portfolio management across all asset classes.',
        'assets.crypto': 'Digital Assets',
        'assets.crypto.desc': 'Explore the future of value. Manage your cryptocurrency portfolio with absolute security and real-time insights.',
        'assets.forex': 'Forex & Currency',
        'assets.forex.desc': 'The power of global currencies. Track exchange rate fluctuations and manage foreign reserves for cross-border journeys.',
        'assets.precious_metals': 'Precious Metals',
        'assets.precious_metals.desc': 'The eternal safe haven. Protect asset value against inflation by storing gold, silver, platinum, and rare precious metals.',
        'assets.gold': 'Precious Metals',
        'assets.gold.desc': 'The eternal safe haven. Protect asset value against inflation by storing gold, silver, and rare precious metals.',
        'assets.stocks': 'Stock Market',
        'assets.stocks.desc': 'Accompany global growth. Analyze stock portfolios, ETFs, and market indices with real-time data.',
        'assets.cash': 'Cash',
        'assets.cash.desc': 'Resources ready for every opportunity. Track cash flow and payment accounts transparently and instantly.',
        'assets.savings': 'Smart Savings',
        'assets.savings.desc': 'The foundation for financial peace of mind. Optimize savings deposits and certificates with the best interest rates.',
        'assets.realestate': 'Real Estate',
        'assets.realestate.desc': 'Value that endures through time. Digitize your portfolio of land, apartments, and long-term real estate investments.',
        'assets.alternative': 'Investments',
        'assets.alternative.desc': 'Expand beyond traditional assets. Diversify your portfolio with P2P lending, venture capital, private equity, and emerging investment opportunities.',
        'assets.collectibles': 'The Collectibles',
        'assets.collectibles.desc': 'Where passion crystallizes into value. Manage unique assets from luxury watches to limited edition collections.',

        // Asset Description
        'assets.description': 'Track and manage diverse asset classes in one unified platform. {highlight} represents a key component of modern portfolio diversification.',
        'assets.highlight.crypto': 'Digital Assets',
        'assets.highlight.forex': 'Forex',
        'assets.highlight.precious-metals': 'Precious Metals',
        'assets.highlight.stocks': 'Stocks',
        'assets.highlight.cash': 'Cash',
        'assets.highlight.savings': 'Savings',
        'assets.highlight.realestate': 'Real Estate',
        'assets.highlight.alternative': 'Alternative Investments',
        'assets.highlight.collectibles': 'Collectibles',

        'footer.product': 'Product',
        'footer.company': 'Company',
        'footer.legal': 'Legal',
        'footer.copyright': 'All rights reserved.',

        // Login Page
        'login.back': '← Back to Home',
        'login.title': 'Login',
        'login.subtitle': 'Sign in and stay ahead of every market move.',
        'login.email': 'Email',
        'login.email.placeholder': 'name@example.com',
        'login.password': 'Password',
        'login.password.forgot': 'Forgot Password?',
        'login.password.placeholder': '••••••••',
        'login.remember': 'Remember Me',
        'login.submit': 'Login',
        'login.or': 'OR CONTINUE WITH',
        'login.google': 'Continue with Google',
        'login.noaccount': "Don't have an account?",
        'login.signup': 'Sign up',

        // Signup Page
        'signup.back': '← Back to Home',
        'signup.title': 'Create Account',
        'signup.subtitle': 'Join YourFin to start managing your wealth.',
        'signup.firstName': 'First Name',
        'signup.firstName.placeholder': 'John',
        'signup.lastName': 'Last Name',
        'signup.lastName.placeholder': 'Doe',
        'signup.email': 'Email',
        'signup.email.placeholder': 'name@example.com',
        'signup.phone': 'Phone Number',
        'signup.phone.placeholder': '+1 234 567 8900',
        'signup.password': 'Password',
        'signup.password.placeholder': '••••••••',
        'signup.confirmPassword': 'Confirm Password',
        'signup.confirmPassword.placeholder': '••••••••',
        'signup.dateOfBirth': 'Date of Birth (Optional)',
        'signup.age': 'Age (Optional)',
        'signup.occupation': 'Occupation (Optional)',
        'signup.occupation.placeholder': 'Software Engineer',
        'signup.submit': 'Create Account',
        'signup.or': 'OR SIGN UP WITH',
        'auth.signup.desc': 'Sign up for a secure account to access all features.',
        'auth.signup.login': 'Already have an account?',
        'auth.signup.login_action': 'Log In',

        // Error & Not Found Pages
        'error.404': 'Error 404',
        'error.not_found': 'Page not found.',
        'error.not_found_desc': 'The page you are looking for does not exist or has been moved to a different location.',
        'error.back_home': 'Back to Home',
        'error.go_back': 'Go Back',
        'error.unexpected': 'Something went wrong',
        'error.unexpected_title': 'Unexpected error.',
        'error.unexpected_desc': 'An unexpected error has occurred. Please try again or return to the homepage.',
        'error.try_again': 'Try Again',

        // Dashboard Layout & Generic
        'dash.nav.overview': 'Overview',
        'dash.nav.portfolio': 'Portfolio',
        'dash.nav.markets': 'Markets',
        'dash.nav.notifications': 'Notifications',
        'dash.nav.profile': 'Profile',
        'dash.nav.settings': 'Settings',
        'dash.nav.news': 'News',
        'dash.nav.learn': 'Learn',
        'dash.nav.history': 'History',
        'dash.nav.analytics': 'Analytics',
        'dash.premium': 'Premium Tier',
        'dash.view_profile': 'View Profile',
        'dash.logout': 'Logout',
        'dash.deposit': 'Deposit Funds',
        'dash.title': 'Dashboard',
        'dash.welcome': 'Welcome back, John!',
        'dash.search': 'SEARCH ASSETS',

        // Dashboard Page
        'dash.total_value': 'Total Portfolio Value',
        'dash.today_pl': 'Today\'s P/L',
        'dash.this_month': 'this month',
        'dash.total_assets': 'Total Assets',
        'dash.risk_score': 'All Time Return',
        'assets.bonds': 'Bonds',
        'dash.risk.moderate': 'Moderate',
        'dash.perf.title': 'Portfolio Performance',
        'dash.perf.desc': 'Real-time asset price tracking',
        'dash.ai.title': 'AI Portfolio Insights',
        'dash.ai.desc': 'Smart recommendations to optimize your holdings based on current market conditions.',
        'dash.ai.div.title': 'Portfolio Diversification',
        'dash.ai.div.desc': 'Consider adding precious metals (Gold, Silver) to protect against inflation risks in the current economic cycle.',
        'dash.ai.div.action': 'Action: Allocate 10% to Gold',
        'dash.ai.risk.title': 'Asset Allocation',
        'dash.ai.risk.desc': 'Your tech stock allocation exceeds 45%. We recommend monitoring NASDAQ volatility closely.',
        'dash.ai.risk.action': 'Action: Rebalance to max 35%',

        // Goals Section
        'dash.goals.title': 'My Goals',
        'dash.goals.add': 'Add Goal',
        'dash.goals.target': 'Target',
        'dash.goals.of': 'of',
        'dash.goals.on_track': 'On Track',
        'dash.goals.behind': 'Behind',
        'dash.goals.1.name': 'Swiss Holiday',
        'dash.goals.2.name': 'Emergency Fund',
        'dash.goals.3.name': 'New Car',

        // Portfolio Health Section
        'dash.health.title': 'Portfolio Health',
        'dash.health.risk_score': 'Risk Score',
        'dash.health.stability': 'Stability improved by',
        'dash.health.desc': 'Your current portfolio risk profile is within the optimal range for your target return profile. Diversification across asset classes remains strong.',
        'dash.health.diversification': 'Diversification',
        'dash.health.liquidity': 'Liquidity',
        'dash.health.volatility': 'Volatility Protection',

        // Profile Page
        'profile.title': 'Profile Settings',
        'profile.subtitle': 'Manage your personal information and account preferences',
        'profile.edit': 'Edit Profile',
        'profile.save': 'Save',
        'profile.cancel': 'Cancel',
        'profile.first_name': 'First Name',
        'profile.last_name': 'Last Name',
        'profile.email': 'Email Address',
        'profile.phone': 'Phone Number',
        'profile.dob': 'Date of Birth',
        'profile.age': 'Age',
        'profile.occupation': 'Occupation',
        'profile.location': 'Location',
        'profile.bio': 'Bio',
        'profile.acc_info': 'Account Information',
        'profile.user_id': 'User ID',
        'profile.member_since': 'Member Since',
        'profile.danger': 'Danger Zone',
        'profile.danger.desc': 'Once you delete your account, there is no going back. Please be certain.',
        'profile.delete': 'Delete Account',
        'profile.delete.modal.title': 'Delete Account?',
        'profile.delete.modal.desc': 'This action cannot be undone. This will permanently delete your account and remove your data from our servers.',
        'profile.placeholder.first_name': 'Enter your first name',
        'profile.placeholder.last_name': 'Enter your last name',
        'profile.placeholder.email': 'Enter your email',
        'profile.placeholder.phone': 'Enter your phone number',
        'profile.placeholder.location': 'Enter your location',
        'profile.placeholder.bio': 'Tell us about yourself...',
        'profile.placeholder.age': 'Enter your age',
        'profile.placeholder.occupation': 'Enter your occupation',
    },
    vi: {
        'nav.features': 'Tính năng',
        'nav.assets': 'Tài sản',
        'nav.pricing': 'Bảng giá',
        'nav.about': 'Về chúng tôi',
        'nav.signin': 'Đăng nhập',
        'nav.getstarted': 'Bắt đầu',
        'hero.scroll': 'Cuộn xuống',
        'intro.title': 'Quản lý tài sản',
        'intro.subtitle': 'thông minh hơn.',
        'intro.description': 'Nền tảng quản lý tài chính cá nhân và theo dõi bảng giá realtime cao cấp nhất dành cho bạn. Thiết kế tối giản, tập trung vào dữ liệu cốt lõi.',
        'intro.cta.primary': 'Bắt đầu ngay',
        'intro.cta.secondary': 'Khám phá tính năng',
        'features.title': 'Mọi thứ bạn cần.',
        'features.subtitle': 'Kiểm soát hoàn toàn bức tranh tài chính của bạn.',
        'features.realtime': 'Bảng điều khiển Realtime',
        'features.realtime.desc': 'Giá trị tài sản được cập nhật mỗi giây với độ trễ bằng 0.',
        'features.multiasset': 'Đa Tài Sản',
        'features.multiasset.desc': 'Theo dõi crypto, forex, vàng và cổ phiếu Việt Nam—tất cả trong một danh mục đầu tư thống nhất.',
        'features.pl': 'Theo dõi Lãi/Lỗ',
        'features.pl.desc': 'Tính toán lãi/lỗ realtime.',
        'features.advisor': 'Tư vấn Danh mục AI',
        'features.advisor.desc': 'Đề xuất thông minh để tối ưu phân bổ danh mục đầu tư dựa trên điều kiện thị trường và hồ sơ rủi ro của bạn.',
        'features.news': 'Cập nhật Tin tức Tài sản',
        'features.news.desc': 'Luôn cập nhật với tin tức và phân tích thị trường realtime cho tất cả tài sản bạn theo dõi.',

        // Asset Types
        'assets.title': 'Theo dõi Mọi Tài sản',
        'assets.subtitle': 'Quản lý danh mục toàn diện trên tất cả các loại tài sản.',
        'assets.crypto': 'Tài sản số',
        'assets.crypto.desc': 'Khám phá tương lai của giá trị. Quản lý danh mục tiền mã hóa với bảo mật tuyệt đối và thông tin thời gian thực.',
        'assets.forex': 'Ngoại hối',
        'assets.forex.desc': 'Sức mạnh của tiền tệ toàn cầu. Theo dõi biến động tỷ giá và quản lý nguồn ngoại tệ dự phòng.',
        'assets.precious_metals': 'Kim loại quý',
        'assets.precious_metals.desc': 'Vịnh tránh bão vĩnh cửu. Bảo vệ giá trị tài sản trước lạm phát bằng vàng, bạc, bạch kim và kim loại quý hiếm.',
        'assets.gold': 'Kim loại quý',
        'assets.gold.desc': 'Vịnh tránh bão vĩnh cửu. Bảo vệ giá trị tài sản trước lạm phát bằng vàng, bạc và kim loại quý hiếm.',
        'assets.stocks': 'Chứng khoán',
        'assets.stocks.desc': 'Đồng hành cùng sự tăng trưởng toàn cầu. Phân tích danh mục cổ phiếu, quỹ ETF với dữ liệu thời gian thực.',
        'assets.cash': 'Tiền mặt',
        'assets.cash.desc': 'Nguồn lực sẵn sàng cho mọi cơ hội. Theo dõi dòng tiền lưu động và tài khoản thanh toán minh bạch, tức thời.',
        'assets.savings': 'Tiết kiệm thông minh',
        'assets.savings.desc': 'Nền móng cho sự an tâm tài chính. Tối ưu hóa tiền gửi tiết kiệm với mức lãi suất tốt nhất.',
        'assets.realestate': 'Bất động sản',
        'assets.realestate.desc': 'Giá trị trường tồn theo thời gian. Số hóa danh mục nhà đất, căn hộ và dự án đầu tư dài hạn.',
        'assets.alternative': 'Đầu tư',
        'assets.alternative.desc': 'Mở rộng ngoài tài sản truyền thống. Đa dạng hóa danh mục với cho vay P2P, vốn mạo hiểm, cổ phần tư nhân và cơ hội đầu tư mới nổi.',
        'assets.collectibles': 'Sưu tầm',
        'assets.collectibles.desc': 'Nơi đam mê kết tinh thành giá trị. Quản lý tài sản độc bản từ đồng hồ xa xỉ đến bộ sưu tập giới hạn.',

        // Asset Description
        'assets.description': 'Theo dõi và quản lý các loại tài sản đa dạng trên một nền tảng thống nhất. {highlight} là thành phần quan trọng trong danh mục đầu tư hiện đại.',
        'assets.highlight.crypto': 'Tài sản số',
        'assets.highlight.forex': 'Ngoại hối',
        'assets.highlight.precious-metals': 'Kim loại quý',
        'assets.highlight.stocks': 'Chứng khoán',
        'assets.highlight.cash': 'Tiền mặt',
        'assets.highlight.savings': 'Tiết kiệm',
        'assets.highlight.realestate': 'Bất động sản',
        'assets.highlight.alternative': 'Đầu tư thay thế',
        'assets.highlight.collectibles': 'Sưu tầm',

        'footer.product': 'Sản phẩm',
        'footer.company': 'Công ty',
        'footer.legal': 'Pháp lý',
        'footer.copyright': 'Mọi quyền được bảo lưu.',

        // Login Page
        'login.back': '← Quay lại Trang chủ',
        'login.title': 'Đăng nhập',
        'login.subtitle': 'Đăng nhập để luôn dẫn trước mọi nhịp thị trường.',
        'login.email': 'Email',
        'login.email.placeholder': 'ten@vidu.com',
        'login.password': 'Mật khẩu',
        'login.password.forgot': 'Quên mật khẩu?',
        'login.password.placeholder': '••••••••',
        'login.remember': 'Ghi nhớ đăng nhập',
        'login.submit': 'Đăng nhập',
        'login.or': 'HOẶC TIẾP TỤC VỚI',
        'login.google': 'Tiếp tục với Google',
        'login.noaccount': "Chưa có tài khoản?",
        'login.signup': 'Đăng ký',

        // Signup Page
        'signup.back': '← Quay lại Trang chủ',
        'signup.title': 'Tạo Tài Khoản',
        'signup.subtitle': 'Tham gia YourFin để bắt đầu quản lý tài sản của bạn.',
        'signup.firstName': 'Họ',
        'signup.firstName.placeholder': 'Nguyễn',
        'signup.lastName': 'Tên',
        'signup.lastName.placeholder': 'Văn A',
        'signup.email': 'Email',
        'signup.email.placeholder': 'ten@vidu.com',
        'signup.phone': 'Số Điện Thoại',
        'signup.phone.placeholder': '0123 456 789',
        'signup.password': 'Mật khẩu',
        'signup.password.placeholder': '••••••••',
        'signup.confirmPassword': 'Xác nhận Mật khẩu',
        'signup.confirmPassword.placeholder': '••••••••',
        'signup.dateOfBirth': 'Ngày Sinh (Tùy chọn)',
        'signup.age': 'Tuổi (Tùy chọn)',
        'signup.occupation': 'Nghề Nghiệp (Tùy chọn)',
        'signup.occupation.placeholder': 'Kỹ sư Phần mềm',
        'signup.submit': 'Tạo Tài Khoản',
        'signup.or': 'HOẶC ĐĂNG KÝ VỚI',
        'auth.signup.desc': 'Đăng ký tài khoản bảo mật để truy cập tất cả các tính năng.',
        'auth.signup.login': 'Đã có tài khoản?',
        'auth.signup.login_action': 'Đăng nhập',

        // Error & Not Found Pages
        'error.404': 'Lỗi 404',
        'error.not_found': 'Không tìm thấy trang.',
        'error.not_found_desc': 'Trang bạn đang tìm kiếm không tồn tại hoặc đã được chuyển sang một địa chỉ khác.',
        'error.back_home': 'Về trang chủ',
        'error.go_back': 'Quay lại',
        'error.unexpected': 'Đã có lỗi xảy ra',
        'error.unexpected_title': 'Lỗi không mong muốn.',
        'error.unexpected_desc': 'Đã có một lỗi không mong muốn xảy ra. Vui lòng thử lại hoặc trở về trang chủ.',
        'error.try_again': 'Thử lại',

        // Dashboard Layout & Generic
        'dash.nav.overview': 'Tổng quan',
        'dash.nav.portfolio': 'Danh mục',
        'dash.nav.markets': 'Thị trường',
        'dash.nav.notifications': 'Thông báo',
        'dash.nav.profile': 'Hồ sơ',
        'dash.nav.settings': 'Cài đặt',
        'dash.nav.news': 'Tin tức',
        'dash.nav.learn': 'Học tập',
        'dash.nav.history': 'Lịch sử',
        'dash.nav.analytics': 'Phân tích',
        'dash.premium': 'Gói Premium',
        'dash.view_profile': 'Xem hồ sơ',
        'dash.logout': 'Đăng xuất',
        'dash.deposit': 'Nạp tiền',
        'dash.title': 'Bảng điều khiển',
        'dash.welcome': 'Chào mừng trở lại, John!',
        'dash.search': 'TÌM KIẾM TÀI SẢN',

        // Dashboard Page
        'dash.total_value': 'Tổng giá trị tài sản',
        'dash.today_pl': 'Lãi/Lỗ hôm nay',
        'dash.this_month': 'tháng này',
        'dash.total_assets': 'Tổng số tài sản',
        'dash.risk_score': 'Lợi nhuận toàn thời gian',
        'assets.bonds': 'Trái phiếu',
        'dash.risk.moderate': 'Trung bình',
        'dash.perf.title': 'Hiệu suất danh mục',
        'dash.perf.desc': 'Theo dõi giá tài sản theo thời gian thực',
        'dash.ai.title': 'Phân tích danh mục AI',
        'dash.ai.desc': 'Đề xuất thông minh giúp tối ưu hóa danh mục đầu tư dựa trên điều kiện thị trường hiện tại.',
        'dash.ai.div.title': 'Đa dạng hóa danh mục',
        'dash.ai.div.desc': 'Cân nhắc bổ sung kim loại quý (Vàng, Bạc) để bảo vệ chống lại rủi ro lạm phát trong chu kỳ kinh tế hiện tại.',
        'dash.ai.div.action': 'Hành động: Phân bổ 10% vào Vàng',
        'dash.ai.risk.title': 'Phân bổ tài sản',
        'dash.ai.risk.desc': 'Tỷ trọng cổ phiếu công nghệ của bạn đang vượt quá 45%. Khuyên bạn theo dõi sát sao biến động của sàn NASDAQ.',
        'dash.ai.risk.action': 'Hành động: Tái cân bằng tối đa 35%',

        // Goals Section
        'dash.goals.title': 'Mục tiêu của tôi',
        'dash.goals.add': 'Thêm mục tiêu',
        'dash.goals.target': 'Mục tiêu',
        'dash.goals.of': 'trên',
        'dash.goals.on_track': 'Đúng tiến độ',
        'dash.goals.behind': 'Chậm tiến độ',
        'dash.goals.1.name': 'Du lịch Thuỵ Sĩ',
        'dash.goals.2.name': 'Quỹ khẩn cấp',
        'dash.goals.3.name': 'Xe mới',

        // Portfolio Health Section
        'dash.health.title': 'Sức khoẻ danh mục',
        'dash.health.risk_score': 'Điểm rủi ro',
        'dash.health.stability': 'Ổn định cải thiện',
        'dash.health.desc': 'Hồ sơ rủi ro danh mục hiện tại nằm trong phạm vi tối ưu cho mục tiêu lợi nhuận. Đa dạng hoá giữa các loại tài sản vẫn mạnh.',
        'dash.health.diversification': 'Đa dạng hoá',
        'dash.health.liquidity': 'Thanh khoản',
        'dash.health.volatility': 'Bảo vệ biến động',

        // Profile Page
        'profile.title': 'Cài đặt Hồ sơ',
        'profile.subtitle': 'Quản lý thông tin cá nhân và tài khoản của bạn',
        'profile.edit': 'Sửa hồ sơ',
        'profile.save': 'Lưu',
        'profile.cancel': 'Hủy',
        'profile.first_name': 'Tên',
        'profile.last_name': 'Họ',
        'profile.email': 'Địa chỉ Email',
        'profile.phone': 'Số điện thoại',
        'profile.dob': 'Ngày sinh',
        'profile.age': 'Tuổi',
        'profile.occupation': 'Nghề nghiệp',
        'profile.location': 'Địa điểm',
        'profile.bio': 'Giới thiệu',
        'profile.acc_info': 'Thông tin Tài khoản',
        'profile.user_id': 'ID Người dùng',
        'profile.member_since': 'Ngày tham gia',
        'profile.danger': 'Vùng nguy hiểm',
        'profile.danger.desc': 'Khi bạn xóa tài khoản, mọi dữ liệu không thể được khôi phục. Vui lòng chắc chắn.',
        'profile.delete': 'Xóa tài khoản',
        'profile.delete.modal.title': 'Xóa tài khoản?',
        'profile.delete.modal.desc': 'Hành động này không thể hoàn tác. Dữ liệu của bạn sẽ bị xóa vĩnh viễn khỏi hệ thống.',
        'profile.placeholder.first_name': 'Nhập tên của bạn',
        'profile.placeholder.last_name': 'Nhập họ của bạn',
        'profile.placeholder.email': 'Nhập email của bạn',
        'profile.placeholder.phone': 'Nhập số điện thoại',
        'profile.placeholder.location': 'Nhập địa điểm',
        'profile.placeholder.bio': 'Kể một chút về bạn...',
        'profile.placeholder.age': 'Nhập tuổi',
        'profile.placeholder.occupation': 'Nhập nghề nghiệp',
    },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguage] = useState<Language>('en');

    const t = (key: string): string => {
        const trans = translations[language] as Record<string, string>;
        return trans[key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}
